# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/kypd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd || ORIG_REF_NAME==kypd} -quiet] -quiet

# IP: D:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_processing_system7_0_1/kypd_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_processing_system7_0_1 || ORIG_REF_NAME==kypd_processing_system7_0_1} -quiet] -quiet

# IP: D:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_PmodKYPD_0_0/kypd_PmodKYPD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_PmodKYPD_0_0 || ORIG_REF_NAME==kypd_PmodKYPD_0_0} -quiet] -quiet

# IP: D:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_ps7_0_axi_periph_0/kypd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_ps7_0_axi_periph_0 || ORIG_REF_NAME==kypd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: D:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_rst_ps7_0_50M_0/kypd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_rst_ps7_0_50M_0 || ORIG_REF_NAME==kypd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: d:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_auto_pc_0/kypd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kypd_auto_pc_0 || ORIG_REF_NAME==kypd_auto_pc_0} -quiet] -quiet

# XDC: D:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/kypd_ooc.xdc
