# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_processing_system7_0_1/kypd_processing_system7_0_1.xci
# IP: The module: 'kypd_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_processing_system7_0_1/kypd_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'kypd_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_processing_system7_0_1/kypd_processing_system7_0_1.xci
# IP: The module: 'kypd_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_processing_system7_0_1/kypd_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'kypd_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
