# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_rst_ps7_0_50M_0/kypd_rst_ps7_0_50M_0.xci
# IP: The module: 'kypd_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_rst_ps7_0_50M_0/kypd_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kypd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_rst_ps7_0_50M_0/kypd_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kypd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_rst_ps7_0_50M_0/kypd_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kypd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_rst_ps7_0_50M_0/kypd_rst_ps7_0_50M_0.xci
# IP: The module: 'kypd_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_rst_ps7_0_50M_0/kypd_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kypd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_rst_ps7_0_50M_0/kypd_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kypd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/VIVADO_Project/ECE520/ECE_520_Final_Project/hardware/bd/kypd/ip/kypd_rst_ps7_0_50M_0/kypd_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kypd_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
